global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: otel-metrics
    static_configs:
      - targets: ["collector:8889"]

  - job_name: services
    static_configs:
      - targets: ["api:8080"]
    scrape_interval: 20s

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]
