using Common.Enums;
using JetBrains.Annotations;

namespace API.DTOs;

/// <summary>
/// A record of who won and lost a match
/// </summary>
/// <remarks>
/// Generated by the o!TR Processor
/// </remarks>
[UsedImplicitly(ImplicitUseTargetFlags.Members)]
public class MatchWinRecordDTO
{
    /// <summary>
    /// The id of the match
    /// </summary>
    public int MatchId { get; set; }

    /// <summary>
    /// Indicates whether the match ended in a tie
    /// </summary>
    public bool IsTied { get; set; }
    /// <summary>
    /// The ids of each player on the losing team. Null if tied.
    /// </summary>
    public int[]? LoserRoster { get; set; } = [];
    /// <summary>
    /// The ids of each player on the winning team. Null if tied.
    /// </summary>
    public int[]? WinnerRoster { get; set; } = [];
    /// <summary>
    /// The number of points the losing team earned
    /// </summary>
    public int LoserPoints { get; set; }
    /// <summary>
    /// The number of points the winning team earned
    /// </summary>
    public int WinnerPoints { get; set; }
    /// <summary>
    /// The winning team (see <see cref="Team"/>). Null if HeadToHead or tied.
    /// </summary>
    public int? WinnerTeam { get; set; }
    /// <summary>
    /// The losing team (see <see cref="Team"/>). Null if HeadToHead or tied.
    /// </summary>
    public int? LoserTeam { get; set; }
}
