using API.Entities;
using API.Osu;
using API.Osu.AutomationChecks;
using API.Osu.Multiplayer;
using Newtonsoft.Json;

namespace APITests.Osu;

public class MatchAutomationChecks_Warmups
{
    private static readonly OsuApiMatchData _matchData = JsonConvert.DeserializeObject<OsuApiMatchData>(
        _json
    )!;
    private static readonly Match _dbMatch = GetMatchForOsuMatch(_matchData);

    [Fact]
    public void Ensure_GameFailure_BadTeamSize()
    {
        Game game = _dbMatch.Games.First();
        Assert.False(GameAutomationChecks.PassesTeamSizeCheck(game));
    }

    private static Match GetMatchForOsuMatch(OsuApiMatchData matchData)
    {
        var tournament = new Tournament()
        {
            Id = 28,
            Name = "Stage's Tranquility Tournament 3",
            Abbreviation = "STT3",
            ForumUrl = "https://osu.ppy.sh/community/forums/topics/1567938?n=1",
            RankRangeLowerBound = 10000,
            Mode = 0,
            TeamSize = 3
        };

        var match = new Match
        {
            Tournament = tournament,
            MatchId = matchData.OsuApiMatch.MatchId,
            Name = matchData.OsuApiMatch.Name,
            StartTime = matchData.OsuApiMatch.StartTime,
            EndTime = matchData.OsuApiMatch.EndTime,
            Games = new List<Game>()
        };

        foreach (OsuApiGame game in matchData.Games)
        {
            var toAdd = new Game
            {
                GameId = game.GameId,
                Match = match,
                MatchScores = new List<MatchScore>()
            };

            foreach (OsuApiScore? score in matchData.Games.SelectMany(x => x.Scores))
            {
                toAdd.MatchScores.Add(
                    new MatchScore
                    {
                        Team = (int)score.Team,
                        Score = score.PlayerScore,
                        EnabledMods = (int)(score.EnabledMods ?? OsuEnums.Mods.None),
                        Game = toAdd
                    }
                );
            }

            match.Games.Add(toAdd);
        }

        return match;
    }

    private const string _json = """
        {
          "match": {
            "match_id": "102524295",
            "name": "STT3: (:coffee:) vs (White Flag in the Asian Sea)",
            "start_time": "2022-07-24 12:48:53",
            "end_time": "2022-07-24 14:52:44"
          },
          "games": [
            {
              "game_id": "524043050",
              "start_time": "2022-07-24 13:07:12",
              "end_time": "2022-07-24 13:10:39",
              "beatmap_id": "2654458",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "0",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "111913",
                  "maxcombo": "390",
                  "rank": "0",
                  "count50": "44",
                  "count100": "166",
                  "count300": "1044",
                  "countmiss": "89",
                  "countgeki": "175",
                  "countkatu": "43",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "17"
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "8666421",
                  "score": "20056",
                  "maxcombo": "208",
                  "rank": "0",
                  "count50": "38",
                  "count100": "103",
                  "count300": "869",
                  "countmiss": "333",
                  "countgeki": "143",
                  "countkatu": "31",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "11"
                },
                {
                  "slot": "2",
                  "team": "1",
                  "user_id": "2282145",
                  "score": "0",
                  "maxcombo": "0",
                  "rank": "0",
                  "count50": "0",
                  "count100": "0",
                  "count300": "0",
                  "countmiss": "1343",
                  "countgeki": "0",
                  "countkatu": "0",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "1"
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "10484034",
                  "score": "148048",
                  "maxcombo": "556",
                  "rank": "0",
                  "count50": "37",
                  "count100": "229",
                  "count300": "1029",
                  "countmiss": "48",
                  "countgeki": "175",
                  "countkatu": "57",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "0"
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "152729",
                  "maxcombo": "479",
                  "rank": "0",
                  "count50": "24",
                  "count100": "240",
                  "count300": "1030",
                  "countmiss": "49",
                  "countgeki": "148",
                  "countkatu": "86",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "17"
                },
                {
                  "slot": "5",
                  "team": "2",
                  "user_id": "10722794",
                  "score": "122032",
                  "maxcombo": "367",
                  "rank": "0",
                  "count50": "26",
                  "count100": "214",
                  "count300": "1049",
                  "countmiss": "54",
                  "countgeki": "163",
                  "countkatu": "70",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "0"
                },
                {
                  "slot": "6",
                  "team": "2",
                  "user_id": "8500628",
                  "score": "174697",
                  "maxcombo": "544",
                  "rank": "0",
                  "count50": "22",
                  "count100": "138",
                  "count300": "1093",
                  "countmiss": "90",
                  "countgeki": "197",
                  "countkatu": "32",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "17"
                },
                {
                  "slot": "7",
                  "team": "2",
                  "user_id": "2763354",
                  "score": "165377",
                  "maxcombo": "500",
                  "rank": "0",
                  "count50": "24",
                  "count100": "245",
                  "count300": "1028",
                  "countmiss": "46",
                  "countgeki": "159",
                  "countkatu": "76",
                  "perfect": "0",
                  "pass": "0",
                  "enabled_mods": "0"
                }
              ]
            },
            {
              "game_id": "524045705",
              "start_time": "2022-07-24 13:29:05",
              "end_time": "2022-07-24 13:33:59",
              "beatmap_id": "2916949",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "3",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "89239",
                  "maxcombo": "284",
                  "rank": "0",
                  "count50": "19",
                  "count100": "150",
                  "count300": "1363",
                  "countmiss": "17",
                  "countgeki": "379",
                  "countkatu": "87",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "14146602",
                  "score": "152771",
                  "maxcombo": "600",
                  "rank": "0",
                  "count50": "11",
                  "count100": "82",
                  "count300": "1442",
                  "countmiss": "14",
                  "countgeki": "431",
                  "countkatu": "48",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "8666421",
                  "score": "231415",
                  "maxcombo": "1074",
                  "rank": "0",
                  "count50": "5",
                  "count100": "46",
                  "count300": "1495",
                  "countmiss": "3",
                  "countgeki": "465",
                  "countkatu": "24",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "2763354",
                  "score": "71875",
                  "maxcombo": "299",
                  "rank": "0",
                  "count50": "35",
                  "count100": "140",
                  "count300": "1320",
                  "countmiss": "54",
                  "countgeki": "365",
                  "countkatu": "77",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "170186",
                  "maxcombo": "957",
                  "rank": "0",
                  "count50": "16",
                  "count100": "87",
                  "count300": "1434",
                  "countmiss": "12",
                  "countgeki": "418",
                  "countkatu": "58",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "10722794",
                  "score": "29342",
                  "maxcombo": "157",
                  "rank": "0",
                  "count50": "53",
                  "count100": "260",
                  "count300": "1164",
                  "countmiss": "72",
                  "countgeki": "268",
                  "countkatu": "138",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524046642",
              "start_time": "2022-07-24 13:37:00",
              "end_time": "2022-07-24 13:39:22",
              "beatmap_id": "2146132",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "17",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "381880",
                  "maxcombo": "173",
                  "rank": "0",
                  "count50": "2",
                  "count100": "14",
                  "count300": "563",
                  "countmiss": "8",
                  "countgeki": "155",
                  "countkatu": "12",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "8500628",
                  "score": "377797",
                  "maxcombo": "180",
                  "rank": "0",
                  "count50": "3",
                  "count100": "17",
                  "count300": "560",
                  "countmiss": "7",
                  "countgeki": "154",
                  "countkatu": "13",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "14146602",
                  "score": "234779",
                  "maxcombo": "152",
                  "rank": "0",
                  "count50": "2",
                  "count100": "69",
                  "count300": "506",
                  "countmiss": "10",
                  "countgeki": "119",
                  "countkatu": "47",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "2282145",
                  "score": "470072",
                  "maxcombo": "312",
                  "rank": "0",
                  "count50": "1",
                  "count100": "25",
                  "count300": "557",
                  "countmiss": "4",
                  "countgeki": "154",
                  "countkatu": "19",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "381864",
                  "maxcombo": "170",
                  "rank": "0",
                  "count50": "1",
                  "count100": "30",
                  "count300": "551",
                  "countmiss": "5",
                  "countgeki": "151",
                  "countkatu": "21",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "10484034",
                  "score": "329866",
                  "maxcombo": "147",
                  "rank": "0",
                  "count50": "2",
                  "count100": "23",
                  "count300": "553",
                  "countmiss": "9",
                  "countgeki": "150",
                  "countkatu": "17",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524047421",
              "start_time": "2022-07-24 13:43:07",
              "end_time": "2022-07-24 13:46:33",
              "beatmap_id": "3579553",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "9",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "307508",
                  "maxcombo": "295",
                  "rank": "0",
                  "count50": "4",
                  "count100": "12",
                  "count300": "933",
                  "countmiss": "31",
                  "countgeki": "79",
                  "countkatu": "5",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "8666421",
                  "score": "443281",
                  "maxcombo": "368",
                  "rank": "0",
                  "count50": "2",
                  "count100": "4",
                  "count300": "960",
                  "countmiss": "14",
                  "countgeki": "91",
                  "countkatu": "0",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "14146602",
                  "score": "269260",
                  "maxcombo": "236",
                  "rank": "0",
                  "count50": "2",
                  "count100": "10",
                  "count300": "926",
                  "countmiss": "42",
                  "countgeki": "77",
                  "countkatu": "4",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "10722794",
                  "score": "287747",
                  "maxcombo": "183",
                  "rank": "0",
                  "count50": "2",
                  "count100": "8",
                  "count300": "933",
                  "countmiss": "37",
                  "countgeki": "80",
                  "countkatu": "1",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "483293",
                  "maxcombo": "381",
                  "rank": "0",
                  "count50": "2",
                  "count100": "12",
                  "count300": "959",
                  "countmiss": "7",
                  "countgeki": "91",
                  "countkatu": "4",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "2763354",
                  "score": "272614",
                  "maxcombo": "270",
                  "rank": "0",
                  "count50": "2",
                  "count100": "8",
                  "count300": "922",
                  "countmiss": "48",
                  "countgeki": "79",
                  "countkatu": "1",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524048196",
              "start_time": "2022-07-24 13:49:23",
              "end_time": "2022-07-24 13:53:41",
              "beatmap_id": "2985706",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "1",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "409798",
                  "maxcombo": "599",
                  "rank": "0",
                  "count50": "1",
                  "count100": "27",
                  "count300": "1050",
                  "countmiss": "7",
                  "countgeki": "258",
                  "countkatu": "21",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "8500628",
                  "score": "560387",
                  "maxcombo": "1096",
                  "rank": "0",
                  "count50": "3",
                  "count100": "31",
                  "count300": "1044",
                  "countmiss": "7",
                  "countgeki": "256",
                  "countkatu": "25",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "14146602",
                  "score": "427789",
                  "maxcombo": "717",
                  "rank": "0",
                  "count50": "1",
                  "count100": "39",
                  "count300": "1038",
                  "countmiss": "7",
                  "countgeki": "252",
                  "countkatu": "31",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "10722794",
                  "score": "481797",
                  "maxcombo": "593",
                  "rank": "0",
                  "count50": "0",
                  "count100": "29",
                  "count300": "1054",
                  "countmiss": "2",
                  "countgeki": "261",
                  "countkatu": "24",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "450858",
                  "maxcombo": "890",
                  "rank": "0",
                  "count50": "1",
                  "count100": "56",
                  "count300": "1017",
                  "countmiss": "11",
                  "countgeki": "237",
                  "countkatu": "42",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "10484034",
                  "score": "464107",
                  "maxcombo": "712",
                  "rank": "0",
                  "count50": "2",
                  "count100": "22",
                  "count300": "1058",
                  "countmiss": "3",
                  "countgeki": "262",
                  "countkatu": "20",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524049225",
              "start_time": "2022-07-24 13:57:49",
              "end_time": "2022-07-24 14:01:28",
              "beatmap_id": "2225505",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "3",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "27936",
                  "maxcombo": "89",
                  "rank": "0",
                  "count50": "42",
                  "count100": "145",
                  "count300": "724",
                  "countmiss": "99",
                  "countgeki": "80",
                  "countkatu": "49",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "8666421",
                  "score": "198843",
                  "maxcombo": "388",
                  "rank": "0",
                  "count50": "11",
                  "count100": "24",
                  "count300": "968",
                  "countmiss": "7",
                  "countgeki": "165",
                  "countkatu": "8",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "14146602",
                  "score": "90443",
                  "maxcombo": "229",
                  "rank": "0",
                  "count50": "31",
                  "count100": "66",
                  "count300": "874",
                  "countmiss": "39",
                  "countgeki": "128",
                  "countkatu": "24",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "2763354",
                  "score": "65378",
                  "maxcombo": "324",
                  "rank": "0",
                  "count50": "23",
                  "count100": "74",
                  "count300": "813",
                  "countmiss": "100",
                  "countgeki": "118",
                  "countkatu": "22",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "95438",
                  "maxcombo": "270",
                  "rank": "0",
                  "count50": "29",
                  "count100": "46",
                  "count300": "895",
                  "countmiss": "40",
                  "countgeki": "139",
                  "countkatu": "15",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "10722794",
                  "score": "21794",
                  "maxcombo": "160",
                  "rank": "0",
                  "count50": "83",
                  "count100": "97",
                  "count300": "652",
                  "countmiss": "178",
                  "countgeki": "68",
                  "countkatu": "22",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524050187",
              "start_time": "2022-07-24 14:05:26",
              "end_time": "2022-07-24 14:07:38",
              "beatmap_id": "2342113",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "1",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "174081",
                  "maxcombo": "234",
                  "rank": "0",
                  "count50": "14",
                  "count100": "143",
                  "count300": "724",
                  "countmiss": "16",
                  "countgeki": "140",
                  "countkatu": "62",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "8666421",
                  "score": "427804",
                  "maxcombo": "479",
                  "rank": "0",
                  "count50": "11",
                  "count100": "65",
                  "count300": "815",
                  "countmiss": "6",
                  "countgeki": "178",
                  "countkatu": "30",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "14146602",
                  "score": "325702",
                  "maxcombo": "454",
                  "rank": "0",
                  "count50": "8",
                  "count100": "101",
                  "count300": "780",
                  "countmiss": "8",
                  "countgeki": "152",
                  "countkatu": "54",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "10484034",
                  "score": "254376",
                  "maxcombo": "214",
                  "rank": "0",
                  "count50": "11",
                  "count100": "68",
                  "count300": "804",
                  "countmiss": "14",
                  "countgeki": "167",
                  "countkatu": "39",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "198423",
                  "maxcombo": "256",
                  "rank": "0",
                  "count50": "18",
                  "count100": "147",
                  "count300": "724",
                  "countmiss": "8",
                  "countgeki": "124",
                  "countkatu": "77",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "10722794",
                  "score": "137220",
                  "maxcombo": "214",
                  "rank": "0",
                  "count50": "20",
                  "count100": "225",
                  "count300": "638",
                  "countmiss": "14",
                  "countgeki": "95",
                  "countkatu": "94",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524051009",
              "start_time": "2022-07-24 14:11:52",
              "end_time": "2022-07-24 14:14:34",
              "beatmap_id": "2260036",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "1",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "239287",
                  "maxcombo": "288",
                  "rank": "0",
                  "count50": "5",
                  "count100": "64",
                  "count300": "765",
                  "countmiss": "12",
                  "countgeki": "239",
                  "countkatu": "43",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "8500628",
                  "score": "175260",
                  "maxcombo": "232",
                  "rank": "0",
                  "count50": "12",
                  "count100": "78",
                  "count300": "737",
                  "countmiss": "19",
                  "countgeki": "214",
                  "countkatu": "55",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "14146602",
                  "score": "494240",
                  "maxcombo": "856",
                  "rank": "0",
                  "count50": "7",
                  "count100": "47",
                  "count300": "790",
                  "countmiss": "2",
                  "countgeki": "247",
                  "countkatu": "39",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "2282145",
                  "score": "378943",
                  "maxcombo": "780",
                  "rank": "0",
                  "count50": "15",
                  "count100": "56",
                  "count300": "760",
                  "countmiss": "15",
                  "countgeki": "237",
                  "countkatu": "43",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "504967",
                  "maxcombo": "718",
                  "rank": "0",
                  "count50": "3",
                  "count100": "69",
                  "count300": "774",
                  "countmiss": "0",
                  "countgeki": "236",
                  "countkatu": "57",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "10484034",
                  "score": "408059",
                  "maxcombo": "452",
                  "rank": "0",
                  "count50": "2",
                  "count100": "30",
                  "count300": "811",
                  "countmiss": "3",
                  "countgeki": "266",
                  "countkatu": "24",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524051936",
              "start_time": "2022-07-24 14:19:03",
              "end_time": "2022-07-24 14:22:53",
              "beatmap_id": "1828691",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "17",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "347407",
                  "maxcombo": "367",
                  "rank": "0",
                  "count50": "6",
                  "count100": "58",
                  "count300": "975",
                  "countmiss": "8",
                  "countgeki": "142",
                  "countkatu": "24",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "8500628",
                  "score": "344750",
                  "maxcombo": "305",
                  "rank": "0",
                  "count50": "11",
                  "count100": "47",
                  "count300": "977",
                  "countmiss": "12",
                  "countgeki": "143",
                  "countkatu": "22",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "7153533",
                  "score": "287833",
                  "maxcombo": "392",
                  "rank": "0",
                  "count50": "25",
                  "count100": "82",
                  "count300": "926",
                  "countmiss": "14",
                  "countgeki": "125",
                  "countkatu": "38",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "2282145",
                  "score": "363019",
                  "maxcombo": "589",
                  "rank": "0",
                  "count50": "19",
                  "count100": "83",
                  "count300": "936",
                  "countmiss": "9",
                  "countgeki": "135",
                  "countkatu": "26",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "437929",
                  "maxcombo": "605",
                  "rank": "0",
                  "count50": "1",
                  "count100": "86",
                  "count300": "956",
                  "countmiss": "4",
                  "countgeki": "144",
                  "countkatu": "28",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "10484034",
                  "score": "533057",
                  "maxcombo": "728",
                  "rank": "0",
                  "count50": "2",
                  "count100": "40",
                  "count300": "999",
                  "countmiss": "6",
                  "countgeki": "147",
                  "countkatu": "25",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524052936",
              "start_time": "2022-07-24 14:26:54",
              "end_time": "2022-07-24 14:29:43",
              "beatmap_id": "3040141",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "257",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "70567",
                  "maxcombo": "190",
                  "rank": "0",
                  "count50": "4",
                  "count100": "67",
                  "count300": "507",
                  "countmiss": "5",
                  "countgeki": "145",
                  "countkatu": "48",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "14146602",
                  "score": "95414",
                  "maxcombo": "477",
                  "rank": "0",
                  "count50": "5",
                  "count100": "69",
                  "count300": "495",
                  "countmiss": "14",
                  "countgeki": "138",
                  "countkatu": "47",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "8666421",
                  "score": "102796",
                  "maxcombo": "417",
                  "rank": "0",
                  "count50": "1",
                  "count100": "55",
                  "count300": "519",
                  "countmiss": "8",
                  "countgeki": "156",
                  "countkatu": "39",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "10722794",
                  "score": "32469",
                  "maxcombo": "158",
                  "rank": "0",
                  "count50": "25",
                  "count100": "116",
                  "count300": "417",
                  "countmiss": "25",
                  "countgeki": "110",
                  "countkatu": "69",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "94275",
                  "maxcombo": "480",
                  "rank": "0",
                  "count50": "2",
                  "count100": "110",
                  "count300": "468",
                  "countmiss": "3",
                  "countgeki": "123",
                  "countkatu": "72",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "2763354",
                  "score": "66262",
                  "maxcombo": "312",
                  "rank": "0",
                  "count50": "7",
                  "count100": "116",
                  "count300": "448",
                  "countmiss": "12",
                  "countgeki": "117",
                  "countkatu": "71",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524053680",
              "start_time": "2022-07-24 14:32:34",
              "end_time": "2022-07-24 14:36:15",
              "beatmap_id": "2670818",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "1",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "8500628",
                  "score": "321980",
                  "maxcombo": "577",
                  "rank": "0",
                  "count50": "13",
                  "count100": "127",
                  "count300": "1087",
                  "countmiss": "2",
                  "countgeki": "150",
                  "countkatu": "34",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "7153533",
                  "score": "403749",
                  "maxcombo": "727",
                  "rank": "0",
                  "count50": "9",
                  "count100": "68",
                  "count300": "1149",
                  "countmiss": "3",
                  "countgeki": "161",
                  "countkatu": "24",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "233633",
                  "maxcombo": "396",
                  "rank": "0",
                  "count50": "25",
                  "count100": "127",
                  "count300": "1061",
                  "countmiss": "16",
                  "countgeki": "141",
                  "countkatu": "30",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "10722794",
                  "score": "636507",
                  "maxcombo": "1147",
                  "rank": "0",
                  "count50": "1",
                  "count100": "37",
                  "count300": "1187",
                  "countmiss": "4",
                  "countgeki": "172",
                  "countkatu": "15",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "941919",
                  "maxcombo": "1638",
                  "rank": "0",
                  "count50": "0",
                  "count100": "35",
                  "count300": "1194",
                  "countmiss": "0",
                  "countgeki": "173",
                  "countkatu": "17",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "2763354",
                  "score": "887230",
                  "maxcombo": "1637",
                  "rank": "0",
                  "count50": "0",
                  "count100": "68",
                  "count300": "1161",
                  "countmiss": "0",
                  "countgeki": "160",
                  "countkatu": "30",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524054882",
              "start_time": "2022-07-24 14:42:00",
              "end_time": "2022-07-24 14:44:22",
              "beatmap_id": "2679663",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "257",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "8666421",
                  "score": "164538",
                  "maxcombo": "491",
                  "rank": "0",
                  "count50": "2",
                  "count100": "43",
                  "count300": "819",
                  "countmiss": "5",
                  "countgeki": "300",
                  "countkatu": "30",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "14146602",
                  "score": "143590",
                  "maxcombo": "598",
                  "rank": "0",
                  "count50": "5",
                  "count100": "92",
                  "count300": "770",
                  "countmiss": "2",
                  "countgeki": "275",
                  "countkatu": "54",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "75440",
                  "maxcombo": "314",
                  "rank": "0",
                  "count50": "21",
                  "count100": "127",
                  "count300": "709",
                  "countmiss": "12",
                  "countgeki": "242",
                  "countkatu": "77",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "10722794",
                  "score": "172319",
                  "maxcombo": "690",
                  "rank": "0",
                  "count50": "6",
                  "count100": "56",
                  "count300": "791",
                  "countmiss": "16",
                  "countgeki": "300",
                  "countkatu": "18",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "85907",
                  "maxcombo": "369",
                  "rank": "0",
                  "count50": "10",
                  "count100": "72",
                  "count300": "764",
                  "countmiss": "23",
                  "countgeki": "285",
                  "countkatu": "29",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "2763354",
                  "score": "99858",
                  "maxcombo": "438",
                  "rank": "0",
                  "count50": "4",
                  "count100": "78",
                  "count300": "767",
                  "countmiss": "20",
                  "countgeki": "279",
                  "countkatu": "42",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": null
                }
              ]
            },
            {
              "game_id": "524055846",
              "start_time": "2022-07-24 14:49:15",
              "end_time": "2022-07-24 14:51:21",
              "beatmap_id": "1768093",
              "play_mode": "0",
              "match_type": "0",
              "scoring_type": "3",
              "team_type": "2",
              "mods": "0",
              "scores": [
                {
                  "slot": "0",
                  "team": "2",
                  "user_id": "8666421",
                  "score": "662839",
                  "maxcombo": "347",
                  "rank": "0",
                  "count50": "0",
                  "count100": "10",
                  "count300": "404",
                  "countmiss": "1",
                  "countgeki": "91",
                  "countkatu": "7",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "9"
                },
                {
                  "slot": "1",
                  "team": "2",
                  "user_id": "7153533",
                  "score": "379650",
                  "maxcombo": "167",
                  "rank": "0",
                  "count50": "1",
                  "count100": "14",
                  "count300": "393",
                  "countmiss": "7",
                  "countgeki": "78",
                  "countkatu": "14",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "17"
                },
                {
                  "slot": "2",
                  "team": "2",
                  "user_id": "9535265",
                  "score": "463478",
                  "maxcombo": "199",
                  "rank": "0",
                  "count50": "1",
                  "count100": "10",
                  "count300": "399",
                  "countmiss": "5",
                  "countgeki": "84",
                  "countkatu": "9",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "17"
                },
                {
                  "slot": "3",
                  "team": "1",
                  "user_id": "14806365",
                  "score": "540722",
                  "maxcombo": "330",
                  "rank": "0",
                  "count50": "0",
                  "count100": "4",
                  "count300": "402",
                  "countmiss": "9",
                  "countgeki": "89",
                  "countkatu": "4",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "9"
                },
                {
                  "slot": "4",
                  "team": "1",
                  "user_id": "10484034",
                  "score": "399252",
                  "maxcombo": "212",
                  "rank": "0",
                  "count50": "2",
                  "count100": "28",
                  "count300": "380",
                  "countmiss": "5",
                  "countgeki": "74",
                  "countkatu": "20",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "17"
                },
                {
                  "slot": "5",
                  "team": "1",
                  "user_id": "2282145",
                  "score": "498224",
                  "maxcombo": "209",
                  "rank": "0",
                  "count50": "1",
                  "count100": "5",
                  "count300": "403",
                  "countmiss": "6",
                  "countgeki": "89",
                  "countkatu": "4",
                  "perfect": "0",
                  "pass": "1",
                  "enabled_mods": "17"
                }
              ]
            }
          ]
        }
        """;
}
