using System.ComponentModel.DataAnnotations.Schema;
using Database.Enums;

namespace Database.Entities.Processor;

/// <summary>
/// Describes roster information for both teams in a <see cref="Match"/>
/// </summary>
/// <remarks>
/// Generated by the <a href="https://github.com/osu-tournament-rating/otr-processor">o!TR Processor</a>
/// </remarks>
[Table("game_win_records")]
public class GameWinRecord : EntityBase
{
    /// <summary>
    /// List of ids of the players on the winning team
    /// </summary>
    [Column("winners")]
    public int[] Winners { get; init; } = [];

    /// <summary>
    /// List of ids of the players on the losing team
    /// </summary>
    [Column("losers")]
    public int[] Losers { get; init; } = [];

    /// <summary>
    /// The <see cref="Enums.Team"/> that won the game
    /// </summary>
    [Column("winner_team")]
    public Team WinnerTeam { get; init; }

    /// <summary>
    /// The <see cref="Enums.Team"/> that won the game
    /// </summary>
    [Column("loser_team")]
    public Team LoserTeam { get; init; }

    /// <summary>
    /// Id of the <see cref="Entities.Game"/> that the <see cref="GameWinRecord"/> was generated for
    /// </summary>
    [Column("game_id")]
    public int GameId { get; init; }

    /// <summary>
    /// The <see cref="Entities.Game"/> that the <see cref="GameWinRecord"/> was generated for
    /// </summary>
    public Game Game { get; init; } = null!;
}
