using System.ComponentModel.DataAnnotations.Schema;
using Database.Enums;

namespace Database.Entities.Processor;

/// <summary>
/// Describes an individual change to the <see cref="BaseStats.Rating"/> of a <see cref="BaseStats"/>
/// </summary>
/// <remarks>
/// Generated by the <a href="https://github.com/osu-tournament-rating/otr-processor">o!TR Processor</a>
/// <br></br>
/// <br></br>
/// A full collection of <see cref="RatingAdjustment"/>s functionally outline the change in rating over time for a
/// player in a ruleset.
/// Where <see cref="BaseStats"/> describe the final and current rating information, <see cref="RatingAdjustment"/>s
/// describe the changes in rating that bring it to that final state.
/// For example, a single <see cref="RatingAdjustment"/> is created for each <see cref="Match"/> played or elapsed
/// period of decay
/// </remarks>
[Table("rating_adjustments")]
public class RatingAdjustment : EntityBase
{
    /// <summary>
    /// The <see cref="Ruleset"/> that the <see cref="RatingAdjustment"/> was generated for
    /// </summary>
    [Column("ruleset")]
    public Ruleset Ruleset { get; init; }

    /// <summary>
    /// Total change in rating
    /// </summary>
    [Column("rating_adjustment_amount")]
    public double RatingAdjustmentAmount { get; init; }

    /// <summary>
    /// Total change in volatility
    /// </summary>
    [Column("volatility_adjustment_amount")]
    public double VolatilityAdjustmentAmount { get; init; }

    /// <summary>
    /// Rating before the <see cref="RatingAdjustmentAmount"/> is applied
    /// </summary>
    [Column("rating_before")]
    public double RatingBefore { get; init; }

    /// <summary>
    /// Rating after the <see cref="RatingAdjustmentAmount"/> is applied
    /// </summary>
    [Column("rating_after")]
    public double RatingAfter { get; init; }

    /// <summary>
    /// Volatility before the <see cref="VolatilityAdjustmentAmount"/> is applied
    /// </summary>
    [Column("volatility_before")]
    public double VolatilityBefore { get; init; }

    /// <summary>
    /// Volatility after the <see cref="VolatilityAdjustmentAmount"/> is applied
    /// </summary>
    [Column("volatility_after")]
    public double VolatilityAfter { get; init; }

    /// <summary>
    /// Describes the type of adjustment being made
    /// </summary>
    [Column("rating_adjustment_type")]
    public RatingAdjustmentType RatingAdjustmentType { get; init; }

    /// <summary>
    /// Timestamp for when this adjustment was applied
    /// </summary>
    [Column("timestamp")]
    public DateTime Timestamp { get; init; }

    /// <summary>
    /// Id of the <see cref="Player"/> that the <see cref="RatingAdjustment"/> was generated for
    /// </summary>
    [Column("player_id")]
    public int PlayerId { get; init; }

    /// <summary>
    /// The <see cref="Player"/> that the <see cref="RatingAdjustment"/> was generated for
    /// </summary>
    public Player Player { get; init; } = null!;
}
