#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-commit tasks..."

FORMAT_OUTPUT=$(dotnet husky run --group pre-commit 2>&1)

echo "$FORMAT_OUTPUT"

if echo "$FORMAT_OUTPUT" | grep -q "Unable to fix"; then
    echo "Found unfixable violations. Please fix the violations and commit again."
    echo "Generating detailed violation description"
    dotnet husky run --name dotnet-verify-staged
fi

echo "Completed pre-commit tasks"
